name: Testing

on:
  pull_request:
    branches: [dev, featureBranch1]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: eslint . --ext .js, .jsx, .ts, .tsx
